export type orbit = {
    apoapsis: number,
    periapsis: number,
    period: number,
    inclination: number,
    eccentricity: number,
    semimajor_axis: number,
    epoch: Date,
    type?: string,
    mean_motion: number,
    ra_of_asc_node: number,
    arg_of_pericenter: number,
    mean_anomaly: number,
    bstar: number,
}
