export type satellite = {
    _id: string,
    intldes: string,
    norad_cat_id: number,
    object_type: string,
    satname: string,
    country: string,
    launch: Date | string,
    site: string,
    decay: Date | string,
    rcsvalue: number,
    rcs_size: string,
    launch_year: number,
    launch_num: number,
    launch_piece: string,
    current: string,
    object_name: string,
    object_id: string,
    object_number: number,
}
