export type satellite = {
    _id: string,
    intldes: string,
    norad_cat_id: number,
    object_type: string,
    satname: string,
    country: string,
    launch: Date | string,
    site: string,
    decay: Date | string,
    rcsvalue: number,
    rcs_size: string,
    launch_year: number,
    launch_num: number,
    launch_piece: string,
    current: string,
    object_name: string,
    object_id: string,
    object_number: number,
    categories: Array<string>,
    tles: Array<tle>,
    data?: data,
    gp?: gp,
}

export interface gp {
    _id: string,
    norad_cat_id: number,
    originator: string,
    epoch: Date,
    mean_motion: number,
    eccentricity: number,
    inclination: number,
    ra_of_asc_node: number,
    arg_of_pericenter: number,
    mean_anomaly: number,
    ephemeris_type: number,
    classification_type: string,
    element_set_no: number,
    rev_at_epoch: number,
    bstar: number,
    mean_motion_dot: number,
    semimajor_axis: number,
    period: number,
    apoapsis: number,
    periapsis: number,
    tle_line0: string,
    tle_line1: string,
    tle_line2: string,
}

export interface data {
    _id: string,
    alternate_name: string,
    official_name: string,
    un_registry: string,
    country_operator: string,
    operator_owner: string,
    users: string,
    purpose: string,
    detailed_purpose: string,
    orbit_class: string,
    orbit_type: string,
    launch_mass: number,
    dry_mass: number,
    power: number,
    expected_lifetime: number,
    contractor: string,
    contractor_country: string,
    launch_site: string,
    launch_vehicle: string,
    cospar_number: string,
    norad_cat_id: number,
    comments: string,
    radio: Array<radio>,
    description: string,
}

export interface radio {
    satname: string,
    norad_cat_id: number,
    uplink: string,
    downlink: string,
    beacon: string,
    mode: string,
    callsign: string,
    type: string,
}

export interface tle {
    _id?: string,
    tle_line0: string,
    tle_line1: string,
    tle_line2: string,
    source: string,
}
