parser: babel-eslint
env:
  browser: true
  commonjs: true
  es2021: true
  mocha: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
    indent: [error, 4]
    linebreak-style: 0
    global-require: 0

