#!/usr/bin/env node

require('dotenv').config();

const Ignitor = require('./src/packages/Ignitor');

(async () => {
    const app = await require('./app.js')();

    new Ignitor(app)
        .fireNeuron();
})();

