#!/usr/bin/env node

require('dotenv').config();

const Ignitor = require('./src/build/Ignitor').Ignitor;

(async () => {
    const app = await require('./app.js')();

    new Ignitor(app, 'D:/projects/orbitcluster-core/core')
        .neuron()
        .handle(process.argv.splice(2));
})();

